version: '3.7'
services:
  vue:
    container_name: theatre
    build: 
      network: common
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'